/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'author' : Principal,
  'updatedAt' : Time,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'published' : boolean,
  'createdAt' : Time,
  'author' : Principal,
  'updatedAt' : Time,
}
export interface Comment {
  'id' : string,
  'content' : string,
  'createdAt' : Time,
  'author' : Principal,
  'postId' : string,
}
export interface ConsensusMeetingView {
  'id' : string,
  'startTime' : Time,
  'participants' : Array<Principal>,
  'groups' : Array<GroupView>,
  'phaseEndTime' : Time,
  'repDistribution' : Array<[Principal, bigint]>,
  'philDistribution' : Array<[Principal, bigint]>,
  'phase' : ConsensusPhase,
  'phaseStartTime' : Time,
}
export type ConsensusPhase = { 'signup' : null } |
  { 'contribution' : null } |
  { 'ranking' : null } |
  { 'finalize' : null };
export interface Contribution { 'files' : Array<ExternalBlob>, 'text' : string }
export interface CouncilDashboard {
  'responsibilities' : Array<string>,
  'lastCouncilUpdate' : Time,
  'panels' : Array<string>,
}
export interface CouncilMultiSigAction {
  'isExecuted' : boolean,
  'timestamp' : Time,
  'details' : string,
  'completionTimestamp' : [] | [Time],
  'actionId' : string,
  'approvals' : Array<Principal>,
}
export interface DailyRewardConfig {
  'member' : bigint,
  'activeMember' : bigint,
  'nonMember' : bigint,
  'allocationPercentage' : bigint,
}
export interface DailyRewardResponse {
  'allocationPercentage' : bigint,
  'canClaim' : boolean,
  'amount' : bigint,
  'cooldown' : bigint,
}
export type DonationTarget = { 'user' : Principal } |
  { 'treasury' : TreasuryTarget };
export type ExternalBlob = Uint8Array;
export interface GroupView {
  'rankings' : Array<[Principal, Array<Ranking>]>,
  'members' : Array<Principal>,
  'contributions' : Array<[Principal, Contribution]>,
  'consensusReached' : boolean,
}
export type JoinRequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface JoinRequestView {
  'status' : JoinRequestStatus,
  'principal' : Principal,
  'timestamp' : Time,
  'approvals' : Array<Principal>,
}
export interface MembershipStatusResponse {
  'hasPendingRequest' : boolean,
  'isMember' : boolean,
}
export interface Notification {
  'id' : string,
  'title' : string,
  'read' : boolean,
  'recipient' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export interface Proposal {
  'id' : string,
  'status' : ProposalStatus,
  'title' : string,
  'description' : string,
  'author' : Principal,
  'rejections' : Array<Principal>,
  'timestamp' : Time,
  'completionTimestamp' : [] | [Time],
  'approvals' : Array<Principal>,
}
export type ProposalStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface Ranking { 'rank' : bigint, 'participant' : Principal }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SupportedToken {
  'name' : string,
  'symbol' : string,
  'canisterId' : Principal,
}
export type Time = bigint;
export interface Tip {
  'id' : string,
  'tipper' : Principal,
  'createdAt' : Time,
  'recipient' : Principal,
  'amount' : bigint,
  'postId' : string,
}
export interface TokenBalance { 'rep' : bigint, 'phil' : bigint }
export type TokenType = { 'ICP' : null } |
  { 'ICRC1' : { 'symbol' : string, 'canisterId' : Principal } };
export interface TokenomicsConfig {
  'inflationRate' : bigint,
  'initialRewardAmount' : bigint,
  'halvingInterval' : Time,
  'minReward' : bigint,
  'rewardsTreasuryAddress' : string,
  'rewardDecreaseFactor' : bigint,
  'launchDate' : Time,
  'lastHalvingTime' : Time,
  'maxSupply' : bigint,
  'marketingTreasuryAddress' : string,
  'councilTreasuryAddress' : string,
}
export type TransactionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TreasuryBalance {
  'council' : bigint,
  'marketing' : bigint,
  'rewards' : bigint,
}
export type TreasuryTarget = { 'council' : null } |
  { 'marketing' : null } |
  { 'rewards' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserCategory = { 'member' : null } |
  { 'activeMember' : null } |
  { 'nonMember' : null };
export interface UserProfile {
  'bio' : string,
  'principal' : Principal,
  'username' : string,
  'email' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletBalances {
  'icp' : bigint,
  'icrc1Tokens' : Array<[string, bigint]>,
}
export interface WalletTransaction {
  'id' : string,
  'fee' : bigint,
  'status' : TransactionStatus,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
  'tokenType' : TokenType,
  'amount' : bigint,
}
export interface WeeklyREPEntry {
  'balance' : bigint,
  'timestamp' : Time,
  'weekId' : string,
}
export interface WeeklyREPLog {
  'principal' : Principal,
  'entries' : Array<WeeklyREPEntry>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'acceptUCA' : ActorMethod<[], undefined>,
  'addBlogReaction' : ActorMethod<[string], undefined>,
  'addSupportedToken' : ActorMethod<[Principal, string, string], undefined>,
  'advanceConsensusMeetingPhase' : ActorMethod<[string], undefined>,
  'approveCouncilAction' : ActorMethod<[string], undefined>,
  'approveMemberJoinRequest' : ActorMethod<[Principal], undefined>,
  'approveProposal' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateAverageREP' : ActorMethod<[Principal], bigint>,
  'claimDailyReward' : ActorMethod<[], bigint>,
  'createAnnouncement' : ActorMethod<[string, string], string>,
  'createBlogComment' : ActorMethod<[string, string], string>,
  'createBlogPost' : ActorMethod<[string, string], string>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createConsensusMeeting' : ActorMethod<[string], undefined>,
  'createProposal' : ActorMethod<[string, string], string>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'donatePHIL' : ActorMethod<[DonationTarget, bigint], undefined>,
  'editAnnouncement' : ActorMethod<[string, string, string], undefined>,
  'editBlogPost' : ActorMethod<[string, string, string], undefined>,
  'finalizeConsensusMeeting' : ActorMethod<[string], undefined>,
  'forceAdvanceConsensusMeetingPhase' : ActorMethod<[string], undefined>,
  'get12WeekREPHistory' : ActorMethod<[Principal], Array<WeeklyREPEntry>>,
  'getActiveUCA' : ActorMethod<[], string>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllConsensusMeetings' : ActorMethod<[], Array<ConsensusMeetingView>>,
  'getAllJoinRequests' : ActorMethod<[], Array<JoinRequestView>>,
  'getAllMembers' : ActorMethod<[], Array<UserProfile>>,
  'getAllNotificationsForUser' : ActorMethod<[], Array<Notification>>,
  'getAllProposals' : ActorMethod<[], Array<Proposal>>,
  'getAllWeeklyREPLogs' : ActorMethod<[], Array<WeeklyREPLog>>,
  'getAnnouncement' : ActorMethod<[string], [] | [Announcement]>,
  'getAvailableConsensusDistributionPool' : ActorMethod<[], bigint>,
  'getAvailableDailyRewardsPool' : ActorMethod<[], bigint>,
  'getAverageREPForAllMembers' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getBlogCommentsByPost' : ActorMethod<[string], Array<Comment>>,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getBlogReactionCount' : ActorMethod<[string], bigint>,
  'getBlogTipsByPost' : ActorMethod<[string], Array<Tip>>,
  'getCallerCategory' : ActorMethod<[], UserCategory>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConsensusDistributionAllocation' : ActorMethod<[], bigint>,
  'getConsensusMeeting' : ActorMethod<[string], [] | [ConsensusMeetingView]>,
  'getCouncilDashboard' : ActorMethod<[], [] | [CouncilDashboard]>,
  'getCouncilMembers' : ActorMethod<[], Array<Principal>>,
  'getCurrentSupply' : ActorMethod<[], bigint>,
  'getDailyRewardConfig' : ActorMethod<[], DailyRewardConfig>,
  'getDailyRewardEligibility' : ActorMethod<[], DailyRewardResponse>,
  'getLastClaimTime' : ActorMethod<[], Time>,
  'getLastCouncilUpdate' : ActorMethod<[], Time>,
  'getMembershipStatus' : ActorMethod<[], MembershipStatusResponse>,
  'getMintCycleStatus' : ActorMethod<[], bigint>,
  'getPendingCouncilActions' : ActorMethod<[], Array<CouncilMultiSigAction>>,
  'getPendingJoinRequests' : ActorMethod<[], Array<JoinRequestView>>,
  'getProposal' : ActorMethod<[string], [] | [Proposal]>,
  'getRewardAmountForCategory' : ActorMethod<[UserCategory], bigint>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSupportedTokens' : ActorMethod<[], Array<SupportedToken>>,
  'getTokenBalance' : ActorMethod<[Principal], TokenBalance>,
  'getTokenomicsConfig' : ActorMethod<[], TokenomicsConfig>,
  'getTotalBlogTipsForPost' : ActorMethod<[string], bigint>,
  'getTransactionHistory' : ActorMethod<[], Array<WalletTransaction>>,
  'getTreasuryBalances' : ActorMethod<[], TreasuryBalance>,
  'getUnreadNotifications' : ActorMethod<[], Array<Notification>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalances' : ActorMethod<[], WalletBalances>,
  'getWeeklyREPHistoryForAllMembers' : ActorMethod<
    [],
    Array<[Principal, Array<WeeklyREPEntry>]>
  >,
  'getWeeklyREPLog' : ActorMethod<[Principal], [] | [WeeklyREPLog]>,
  'hasAcceptedUCA' : ActorMethod<[], boolean>,
  'hasUserReactedToBlogPost' : ActorMethod<[string], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isCouncilMember' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'leaveCommunity' : ActorMethod<[], undefined>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markNotificationAsRead' : ActorMethod<[string], undefined>,
  'mintRewards' : ActorMethod<[], undefined>,
  'promoteToAdmin' : ActorMethod<[Principal], undefined>,
  'proposeCouncilAction' : ActorMethod<[string, string], undefined>,
  'recalculateCouncilByAverageREP' : ActorMethod<[], undefined>,
  'rejectProposal' : ActorMethod<[string], undefined>,
  'removeSupportedToken' : ActorMethod<[Principal], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendICP' : ActorMethod<[Principal, bigint], string>,
  'sendICRC1Token' : ActorMethod<[Principal, Principal, bigint], string>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'signUpForConsensusMeeting' : ActorMethod<[string], undefined>,
  'submitContribution' : ActorMethod<
    [string, string, Array<ExternalBlob>],
    undefined
  >,
  'submitJoinRequest' : ActorMethod<[], undefined>,
  'submitRanking' : ActorMethod<[string, Array<Ranking>], undefined>,
  'tipBlogPost' : ActorMethod<[string, bigint], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCallerUserProfile' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    undefined
  >,
  'updateConsensusDistributionAllocation' : ActorMethod<[bigint], undefined>,
  'updateDailyRewardConfig' : ActorMethod<[DailyRewardConfig], undefined>,
  'updateJoinRequestStatus' : ActorMethod<
    [Principal, JoinRequestStatus],
    string
  >,
  'updateTokenomicsConfig' : ActorMethod<[TokenomicsConfig], undefined>,
  'updateUCA' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];