/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const TreasuryTarget = IDL.Variant({
  'council' : IDL.Null,
  'marketing' : IDL.Null,
  'rewards' : IDL.Null,
});
export const DonationTarget = IDL.Variant({
  'user' : IDL.Principal,
  'treasury' : TreasuryTarget,
});
export const Time = IDL.Int;
export const WeeklyREPEntry = IDL.Record({
  'balance' : IDL.Nat,
  'timestamp' : Time,
  'weekId' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'updatedAt' : Time,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'updatedAt' : Time,
});
export const Ranking = IDL.Record({
  'rank' : IDL.Nat,
  'participant' : IDL.Principal,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Contribution = IDL.Record({
  'files' : IDL.Vec(ExternalBlob),
  'text' : IDL.Text,
});
export const GroupView = IDL.Record({
  'rankings' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Ranking))),
  'members' : IDL.Vec(IDL.Principal),
  'contributions' : IDL.Vec(IDL.Tuple(IDL.Principal, Contribution)),
  'consensusReached' : IDL.Bool,
});
export const ConsensusPhase = IDL.Variant({
  'signup' : IDL.Null,
  'contribution' : IDL.Null,
  'ranking' : IDL.Null,
  'finalize' : IDL.Null,
});
export const ConsensusMeetingView = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'participants' : IDL.Vec(IDL.Principal),
  'groups' : IDL.Vec(GroupView),
  'phaseEndTime' : Time,
  'repDistribution' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
  'philDistribution' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
  'phase' : ConsensusPhase,
  'phaseStartTime' : Time,
});
export const JoinRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const JoinRequestView = IDL.Record({
  'status' : JoinRequestStatus,
  'principal' : IDL.Principal,
  'timestamp' : Time,
  'approvals' : IDL.Vec(IDL.Principal),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'email' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'read' : IDL.Bool,
  'recipient' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ProposalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Proposal = IDL.Record({
  'id' : IDL.Text,
  'status' : ProposalStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'rejections' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
  'completionTimestamp' : IDL.Opt(Time),
  'approvals' : IDL.Vec(IDL.Principal),
});
export const WeeklyREPLog = IDL.Record({
  'principal' : IDL.Principal,
  'entries' : IDL.Vec(WeeklyREPEntry),
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Principal,
  'postId' : IDL.Text,
});
export const Tip = IDL.Record({
  'id' : IDL.Text,
  'tipper' : IDL.Principal,
  'createdAt' : Time,
  'recipient' : IDL.Principal,
  'amount' : IDL.Nat,
  'postId' : IDL.Text,
});
export const UserCategory = IDL.Variant({
  'member' : IDL.Null,
  'activeMember' : IDL.Null,
  'nonMember' : IDL.Null,
});
export const CouncilDashboard = IDL.Record({
  'responsibilities' : IDL.Vec(IDL.Text),
  'lastCouncilUpdate' : Time,
  'panels' : IDL.Vec(IDL.Text),
});
export const DailyRewardConfig = IDL.Record({
  'member' : IDL.Nat,
  'activeMember' : IDL.Nat,
  'nonMember' : IDL.Nat,
  'allocationPercentage' : IDL.Nat,
});
export const DailyRewardResponse = IDL.Record({
  'allocationPercentage' : IDL.Nat,
  'canClaim' : IDL.Bool,
  'amount' : IDL.Nat,
  'cooldown' : IDL.Nat,
});
export const MembershipStatusResponse = IDL.Record({
  'hasPendingRequest' : IDL.Bool,
  'isMember' : IDL.Bool,
});
export const CouncilMultiSigAction = IDL.Record({
  'isExecuted' : IDL.Bool,
  'timestamp' : Time,
  'details' : IDL.Text,
  'completionTimestamp' : IDL.Opt(Time),
  'actionId' : IDL.Text,
  'approvals' : IDL.Vec(IDL.Principal),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const SupportedToken = IDL.Record({
  'name' : IDL.Text,
  'symbol' : IDL.Text,
  'canisterId' : IDL.Principal,
});
export const TokenBalance = IDL.Record({ 'rep' : IDL.Nat, 'phil' : IDL.Nat });
export const TokenomicsConfig = IDL.Record({
  'inflationRate' : IDL.Nat,
  'initialRewardAmount' : IDL.Nat,
  'halvingInterval' : Time,
  'minReward' : IDL.Nat,
  'rewardsTreasuryAddress' : IDL.Text,
  'rewardDecreaseFactor' : IDL.Nat,
  'launchDate' : Time,
  'lastHalvingTime' : Time,
  'maxSupply' : IDL.Nat,
  'marketingTreasuryAddress' : IDL.Text,
  'councilTreasuryAddress' : IDL.Text,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TokenType = IDL.Variant({
  'ICP' : IDL.Null,
  'ICRC1' : IDL.Record({ 'symbol' : IDL.Text, 'canisterId' : IDL.Principal }),
});
export const WalletTransaction = IDL.Record({
  'id' : IDL.Text,
  'fee' : IDL.Nat,
  'status' : TransactionStatus,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'tokenType' : TokenType,
  'amount' : IDL.Nat,
});
export const TreasuryBalance = IDL.Record({
  'council' : IDL.Nat,
  'marketing' : IDL.Nat,
  'rewards' : IDL.Nat,
});
export const WalletBalances = IDL.Record({
  'icp' : IDL.Nat,
  'icrc1Tokens' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'acceptUCA' : IDL.Func([], [], []),
  'addBlogReaction' : IDL.Func([IDL.Text], [], []),
  'addSupportedToken' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  'advanceConsensusMeetingPhase' : IDL.Func([IDL.Text], [], []),
  'approveCouncilAction' : IDL.Func([IDL.Text], [], []),
  'approveMemberJoinRequest' : IDL.Func([IDL.Principal], [], []),
  'approveProposal' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateAverageREP' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'claimDailyReward' : IDL.Func([], [IDL.Nat], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createBlogComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createBlogPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createConsensusMeeting' : IDL.Func([IDL.Text], [], []),
  'createProposal' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'donatePHIL' : IDL.Func([DonationTarget, IDL.Nat], [], []),
  'editAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'editBlogPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'finalizeConsensusMeeting' : IDL.Func([IDL.Text], [], []),
  'forceAdvanceConsensusMeetingPhase' : IDL.Func([IDL.Text], [], []),
  'get12WeekREPHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WeeklyREPEntry)],
      ['query'],
    ),
  'getActiveUCA' : IDL.Func([], [IDL.Text], ['query']),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllConsensusMeetings' : IDL.Func(
      [],
      [IDL.Vec(ConsensusMeetingView)],
      ['query'],
    ),
  'getAllJoinRequests' : IDL.Func([], [IDL.Vec(JoinRequestView)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllNotificationsForUser' : IDL.Func(
      [],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getAllProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
  'getAllWeeklyREPLogs' : IDL.Func([], [IDL.Vec(WeeklyREPLog)], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Text], [IDL.Opt(Announcement)], ['query']),
  'getAvailableConsensusDistributionPool' : IDL.Func([], [IDL.Nat], ['query']),
  'getAvailableDailyRewardsPool' : IDL.Func([], [IDL.Nat], ['query']),
  'getAverageREPForAllMembers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getBlogCommentsByPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBlogReactionCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getBlogTipsByPost' : IDL.Func([IDL.Text], [IDL.Vec(Tip)], ['query']),
  'getCallerCategory' : IDL.Func([], [UserCategory], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConsensusDistributionAllocation' : IDL.Func([], [IDL.Nat], ['query']),
  'getConsensusMeeting' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ConsensusMeetingView)],
      ['query'],
    ),
  'getCouncilDashboard' : IDL.Func([], [IDL.Opt(CouncilDashboard)], ['query']),
  'getCouncilMembers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCurrentSupply' : IDL.Func([], [IDL.Nat], ['query']),
  'getDailyRewardConfig' : IDL.Func([], [DailyRewardConfig], ['query']),
  'getDailyRewardEligibility' : IDL.Func([], [DailyRewardResponse], ['query']),
  'getLastClaimTime' : IDL.Func([], [Time], ['query']),
  'getLastCouncilUpdate' : IDL.Func([], [Time], ['query']),
  'getMembershipStatus' : IDL.Func([], [MembershipStatusResponse], ['query']),
  'getMintCycleStatus' : IDL.Func([], [IDL.Nat], ['query']),
  'getPendingCouncilActions' : IDL.Func(
      [],
      [IDL.Vec(CouncilMultiSigAction)],
      ['query'],
    ),
  'getPendingJoinRequests' : IDL.Func(
      [],
      [IDL.Vec(JoinRequestView)],
      ['query'],
    ),
  'getProposal' : IDL.Func([IDL.Text], [IDL.Opt(Proposal)], ['query']),
  'getRewardAmountForCategory' : IDL.Func([UserCategory], [IDL.Nat], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSupportedTokens' : IDL.Func([], [IDL.Vec(SupportedToken)], ['query']),
  'getTokenBalance' : IDL.Func([IDL.Principal], [TokenBalance], ['query']),
  'getTokenomicsConfig' : IDL.Func([], [TokenomicsConfig], ['query']),
  'getTotalBlogTipsForPost' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'getTreasuryBalances' : IDL.Func([], [TreasuryBalance], ['query']),
  'getUnreadNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletBalances' : IDL.Func([], [WalletBalances], ['query']),
  'getWeeklyREPHistoryForAllMembers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(WeeklyREPEntry)))],
      ['query'],
    ),
  'getWeeklyREPLog' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(WeeklyREPLog)],
      ['query'],
    ),
  'hasAcceptedUCA' : IDL.Func([], [IDL.Bool], ['query']),
  'hasUserReactedToBlogPost' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isCouncilMember' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveCommunity' : IDL.Func([], [], []),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
  'mintRewards' : IDL.Func([], [], []),
  'promoteToAdmin' : IDL.Func([IDL.Principal], [], []),
  'proposeCouncilAction' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'recalculateCouncilByAverageREP' : IDL.Func([], [], []),
  'rejectProposal' : IDL.Func([IDL.Text], [], []),
  'removeSupportedToken' : IDL.Func([IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendICP' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Text], []),
  'sendICRC1Token' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'signUpForConsensusMeeting' : IDL.Func([IDL.Text], [], []),
  'submitContribution' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(ExternalBlob)],
      [],
      [],
    ),
  'submitJoinRequest' : IDL.Func([], [], []),
  'submitRanking' : IDL.Func([IDL.Text, IDL.Vec(Ranking)], [], []),
  'tipBlogPost' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateConsensusDistributionAllocation' : IDL.Func([IDL.Nat], [], []),
  'updateDailyRewardConfig' : IDL.Func([DailyRewardConfig], [], []),
  'updateJoinRequestStatus' : IDL.Func(
      [IDL.Principal, JoinRequestStatus],
      [IDL.Text],
      [],
    ),
  'updateTokenomicsConfig' : IDL.Func([TokenomicsConfig], [], []),
  'updateUCA' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const TreasuryTarget = IDL.Variant({
    'council' : IDL.Null,
    'marketing' : IDL.Null,
    'rewards' : IDL.Null,
  });
  const DonationTarget = IDL.Variant({
    'user' : IDL.Principal,
    'treasury' : TreasuryTarget,
  });
  const Time = IDL.Int;
  const WeeklyREPEntry = IDL.Record({
    'balance' : IDL.Nat,
    'timestamp' : Time,
    'weekId' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'updatedAt' : Time,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'updatedAt' : Time,
  });
  const Ranking = IDL.Record({
    'rank' : IDL.Nat,
    'participant' : IDL.Principal,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Contribution = IDL.Record({
    'files' : IDL.Vec(ExternalBlob),
    'text' : IDL.Text,
  });
  const GroupView = IDL.Record({
    'rankings' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Ranking))),
    'members' : IDL.Vec(IDL.Principal),
    'contributions' : IDL.Vec(IDL.Tuple(IDL.Principal, Contribution)),
    'consensusReached' : IDL.Bool,
  });
  const ConsensusPhase = IDL.Variant({
    'signup' : IDL.Null,
    'contribution' : IDL.Null,
    'ranking' : IDL.Null,
    'finalize' : IDL.Null,
  });
  const ConsensusMeetingView = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'participants' : IDL.Vec(IDL.Principal),
    'groups' : IDL.Vec(GroupView),
    'phaseEndTime' : Time,
    'repDistribution' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
    'philDistribution' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
    'phase' : ConsensusPhase,
    'phaseStartTime' : Time,
  });
  const JoinRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const JoinRequestView = IDL.Record({
    'status' : JoinRequestStatus,
    'principal' : IDL.Principal,
    'timestamp' : Time,
    'approvals' : IDL.Vec(IDL.Principal),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'email' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'read' : IDL.Bool,
    'recipient' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ProposalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Proposal = IDL.Record({
    'id' : IDL.Text,
    'status' : ProposalStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'rejections' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
    'completionTimestamp' : IDL.Opt(Time),
    'approvals' : IDL.Vec(IDL.Principal),
  });
  const WeeklyREPLog = IDL.Record({
    'principal' : IDL.Principal,
    'entries' : IDL.Vec(WeeklyREPEntry),
  });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Principal,
    'postId' : IDL.Text,
  });
  const Tip = IDL.Record({
    'id' : IDL.Text,
    'tipper' : IDL.Principal,
    'createdAt' : Time,
    'recipient' : IDL.Principal,
    'amount' : IDL.Nat,
    'postId' : IDL.Text,
  });
  const UserCategory = IDL.Variant({
    'member' : IDL.Null,
    'activeMember' : IDL.Null,
    'nonMember' : IDL.Null,
  });
  const CouncilDashboard = IDL.Record({
    'responsibilities' : IDL.Vec(IDL.Text),
    'lastCouncilUpdate' : Time,
    'panels' : IDL.Vec(IDL.Text),
  });
  const DailyRewardConfig = IDL.Record({
    'member' : IDL.Nat,
    'activeMember' : IDL.Nat,
    'nonMember' : IDL.Nat,
    'allocationPercentage' : IDL.Nat,
  });
  const DailyRewardResponse = IDL.Record({
    'allocationPercentage' : IDL.Nat,
    'canClaim' : IDL.Bool,
    'amount' : IDL.Nat,
    'cooldown' : IDL.Nat,
  });
  const MembershipStatusResponse = IDL.Record({
    'hasPendingRequest' : IDL.Bool,
    'isMember' : IDL.Bool,
  });
  const CouncilMultiSigAction = IDL.Record({
    'isExecuted' : IDL.Bool,
    'timestamp' : Time,
    'details' : IDL.Text,
    'completionTimestamp' : IDL.Opt(Time),
    'actionId' : IDL.Text,
    'approvals' : IDL.Vec(IDL.Principal),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const SupportedToken = IDL.Record({
    'name' : IDL.Text,
    'symbol' : IDL.Text,
    'canisterId' : IDL.Principal,
  });
  const TokenBalance = IDL.Record({ 'rep' : IDL.Nat, 'phil' : IDL.Nat });
  const TokenomicsConfig = IDL.Record({
    'inflationRate' : IDL.Nat,
    'initialRewardAmount' : IDL.Nat,
    'halvingInterval' : Time,
    'minReward' : IDL.Nat,
    'rewardsTreasuryAddress' : IDL.Text,
    'rewardDecreaseFactor' : IDL.Nat,
    'launchDate' : Time,
    'lastHalvingTime' : Time,
    'maxSupply' : IDL.Nat,
    'marketingTreasuryAddress' : IDL.Text,
    'councilTreasuryAddress' : IDL.Text,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TokenType = IDL.Variant({
    'ICP' : IDL.Null,
    'ICRC1' : IDL.Record({ 'symbol' : IDL.Text, 'canisterId' : IDL.Principal }),
  });
  const WalletTransaction = IDL.Record({
    'id' : IDL.Text,
    'fee' : IDL.Nat,
    'status' : TransactionStatus,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'tokenType' : TokenType,
    'amount' : IDL.Nat,
  });
  const TreasuryBalance = IDL.Record({
    'council' : IDL.Nat,
    'marketing' : IDL.Nat,
    'rewards' : IDL.Nat,
  });
  const WalletBalances = IDL.Record({
    'icp' : IDL.Nat,
    'icrc1Tokens' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'acceptUCA' : IDL.Func([], [], []),
    'addBlogReaction' : IDL.Func([IDL.Text], [], []),
    'addSupportedToken' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
    'advanceConsensusMeetingPhase' : IDL.Func([IDL.Text], [], []),
    'approveCouncilAction' : IDL.Func([IDL.Text], [], []),
    'approveMemberJoinRequest' : IDL.Func([IDL.Principal], [], []),
    'approveProposal' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateAverageREP' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'claimDailyReward' : IDL.Func([], [IDL.Nat], []),
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createBlogComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createBlogPost' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createConsensusMeeting' : IDL.Func([IDL.Text], [], []),
    'createProposal' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'donatePHIL' : IDL.Func([DonationTarget, IDL.Nat], [], []),
    'editAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'editBlogPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'finalizeConsensusMeeting' : IDL.Func([IDL.Text], [], []),
    'forceAdvanceConsensusMeetingPhase' : IDL.Func([IDL.Text], [], []),
    'get12WeekREPHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WeeklyREPEntry)],
        ['query'],
      ),
    'getActiveUCA' : IDL.Func([], [IDL.Text], ['query']),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllConsensusMeetings' : IDL.Func(
        [],
        [IDL.Vec(ConsensusMeetingView)],
        ['query'],
      ),
    'getAllJoinRequests' : IDL.Func([], [IDL.Vec(JoinRequestView)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllNotificationsForUser' : IDL.Func(
        [],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getAllProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
    'getAllWeeklyREPLogs' : IDL.Func([], [IDL.Vec(WeeklyREPLog)], ['query']),
    'getAnnouncement' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Announcement)],
        ['query'],
      ),
    'getAvailableConsensusDistributionPool' : IDL.Func(
        [],
        [IDL.Nat],
        ['query'],
      ),
    'getAvailableDailyRewardsPool' : IDL.Func([], [IDL.Nat], ['query']),
    'getAverageREPForAllMembers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getBlogCommentsByPost' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBlogReactionCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getBlogTipsByPost' : IDL.Func([IDL.Text], [IDL.Vec(Tip)], ['query']),
    'getCallerCategory' : IDL.Func([], [UserCategory], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConsensusDistributionAllocation' : IDL.Func([], [IDL.Nat], ['query']),
    'getConsensusMeeting' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ConsensusMeetingView)],
        ['query'],
      ),
    'getCouncilDashboard' : IDL.Func(
        [],
        [IDL.Opt(CouncilDashboard)],
        ['query'],
      ),
    'getCouncilMembers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCurrentSupply' : IDL.Func([], [IDL.Nat], ['query']),
    'getDailyRewardConfig' : IDL.Func([], [DailyRewardConfig], ['query']),
    'getDailyRewardEligibility' : IDL.Func(
        [],
        [DailyRewardResponse],
        ['query'],
      ),
    'getLastClaimTime' : IDL.Func([], [Time], ['query']),
    'getLastCouncilUpdate' : IDL.Func([], [Time], ['query']),
    'getMembershipStatus' : IDL.Func([], [MembershipStatusResponse], ['query']),
    'getMintCycleStatus' : IDL.Func([], [IDL.Nat], ['query']),
    'getPendingCouncilActions' : IDL.Func(
        [],
        [IDL.Vec(CouncilMultiSigAction)],
        ['query'],
      ),
    'getPendingJoinRequests' : IDL.Func(
        [],
        [IDL.Vec(JoinRequestView)],
        ['query'],
      ),
    'getProposal' : IDL.Func([IDL.Text], [IDL.Opt(Proposal)], ['query']),
    'getRewardAmountForCategory' : IDL.Func(
        [UserCategory],
        [IDL.Nat],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSupportedTokens' : IDL.Func([], [IDL.Vec(SupportedToken)], ['query']),
    'getTokenBalance' : IDL.Func([IDL.Principal], [TokenBalance], ['query']),
    'getTokenomicsConfig' : IDL.Func([], [TokenomicsConfig], ['query']),
    'getTotalBlogTipsForPost' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'getTreasuryBalances' : IDL.Func([], [TreasuryBalance], ['query']),
    'getUnreadNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletBalances' : IDL.Func([], [WalletBalances], ['query']),
    'getWeeklyREPHistoryForAllMembers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(WeeklyREPEntry)))],
        ['query'],
      ),
    'getWeeklyREPLog' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(WeeklyREPLog)],
        ['query'],
      ),
    'hasAcceptedUCA' : IDL.Func([], [IDL.Bool], ['query']),
    'hasUserReactedToBlogPost' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isCouncilMember' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveCommunity' : IDL.Func([], [], []),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
    'mintRewards' : IDL.Func([], [], []),
    'promoteToAdmin' : IDL.Func([IDL.Principal], [], []),
    'proposeCouncilAction' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'recalculateCouncilByAverageREP' : IDL.Func([], [], []),
    'rejectProposal' : IDL.Func([IDL.Text], [], []),
    'removeSupportedToken' : IDL.Func([IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendICP' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Text], []),
    'sendICRC1Token' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'signUpForConsensusMeeting' : IDL.Func([IDL.Text], [], []),
    'submitContribution' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(ExternalBlob)],
        [],
        [],
      ),
    'submitJoinRequest' : IDL.Func([], [], []),
    'submitRanking' : IDL.Func([IDL.Text, IDL.Vec(Ranking)], [], []),
    'tipBlogPost' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateConsensusDistributionAllocation' : IDL.Func([IDL.Nat], [], []),
    'updateDailyRewardConfig' : IDL.Func([DailyRewardConfig], [], []),
    'updateJoinRequestStatus' : IDL.Func(
        [IDL.Principal, JoinRequestStatus],
        [IDL.Text],
        [],
      ),
    'updateTokenomicsConfig' : IDL.Func([TokenomicsConfig], [], []),
    'updateUCA' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };